steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  env:
    - 'DOCKER_BUILDKIT=1'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/catdogdetection-447911/training-registry/train-image:tag1',
    '-f',
    'dockerfiles/train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/catdogdetection-447911/training-registry/train-image:tag1'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'train-image',
    '--image',
    'europe-west1-docker.pkg.dev/catdogdetection-447911/training-registry/train-image:tag1',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--ingress=all',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
