name: Model Registry Update Workflow

on:
  push:
    paths:
      - 'models/**'

jobs:
  model-change:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        pip install -r requirements.txt
        pip install -r requirements_dev.txt

    - name: Run model update script
      run: |
        invoke evaluate -m M_Exp1
